server:
  port: 8010
spring:
  application:
    name: order-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/goods?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        username: nacos
        password: nacos
        namespace: public
        ephemeral: false  #  永久实例，服务宕机了也不会删除服务列表
        # service : ${application.name} (,默认取值)
        # group:  DEFAULT_GROUP (默认)
        # weight: 1 (默认)
    alibaba:
      seata:
        tx-service-group: NanJing
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.tuling.cloud.entity
  configuration:
    map-underscore-to-camel-case: true

seata:
  registry:
    # 配置 Seata 服务端所在的注册中心地址，让 seata-client(TM) 可以与 seata-server (TC) 进行通信
    type: nacos
    nacos:
      application: seata-server
      server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos
      namespace: seata
      group: SEATA_GROUP  # seata-server 所在的分组，默认值就是 SEATA_GROUP
  config:
    type: nacos
    nacos:
      namespace: seata
      group: SEATA_GROUP
      server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos
